// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ignore_for_file: non_constant_identifier_names

// This file is generated by tool/schema_generator/bin/generate.dart.
// Do not edit this file manually.

import 'package:schemantic/schemantic.dart';
part 'types.g.dart';

@Schema()
abstract class $Candidate {
  double get index;
  $Message get message;
  $GenerationUsage? get usage;
  FinishReason get finishReason;
  String? get finishMessage;
  Map<String, dynamic>? get custom;
}

@Schema()
abstract class $Message {
  Role get role;
  List<$Part> get content;
  Map<String, dynamic>? get metadata;
}

@Schema()
abstract class $ToolDefinition {
  String get name;
  String? get key;
  String get description;
  Map<String, dynamic>? get inputSchema;
  Map<String, dynamic>? get outputSchema;
  Map<String, dynamic>? get metadata;
}

@Schema()
abstract class $Part {}

@Schema()
abstract class $TextPart implements $Part {
  String get text;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schema()
abstract class $MediaPart implements $Part {
  $Media get media;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schema()
abstract class $ToolRequestPart implements $Part {
  $ToolRequest get toolRequest;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schema()
abstract class $ToolResponsePart implements $Part {
  $ToolResponse get toolResponse;
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schema()
abstract class $DataPart implements $Part {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
}

@Schema()
abstract class $CustomPart implements $Part {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic> get custom;
}

@Schema()
abstract class $ReasoningPart implements $Part {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
  String get reasoning;
}

@Schema()
abstract class $ResourcePart implements $Part {
  Map<String, dynamic>? get data;
  Map<String, dynamic>? get metadata;
  Map<String, dynamic>? get custom;
  Map<String, dynamic> get resource;
}

@Schema()
abstract class $BaseDataPoint {
  Map<String, dynamic>? get input;
  Map<String, dynamic>? get output;
  List<Map<String, dynamic>>? get context;
  Map<String, dynamic>? get reference;
  String? get testCaseId;
  List<String>? get traceIds;
}

@Schema()
abstract class $EvalRequest {
  List<$BaseDataPoint> get dataset;
  String get evalRunId;
  Map<String, dynamic>? get options;
}

@Schema()
abstract class $EvalFnResponse {
  double? get sampleIndex;
  String get testCaseId;
  String? get traceId;
  String? get spanId;
  @AnyOf([$Score, List<$Score>])
  Object? get evaluation;
}

extension type EvalStatusEnum(String value) {
  static EvalStatusEnum get UNKNOWN => EvalStatusEnum('UNKNOWN');
  static EvalStatusEnum get PASS => EvalStatusEnum('PASS');
  static EvalStatusEnum get FAIL => EvalStatusEnum('FAIL');
}

@Schema()
abstract class $Score {
  String? get id;
  @AnyOf([double, String, bool])
  Object? get score;
  EvalStatusEnum? get status;
  String? get error;
  Map<String, dynamic>? get details;
}

@Schema()
abstract class $Media {
  String? get contentType;
  String get url;
}

@Schema()
abstract class $ToolRequest {
  String? get ref;
  String get name;
  Object? get input;
  bool? get partial;
}

@Schema()
abstract class $ToolResponse {
  String? get ref;
  String get name;
  dynamic get output;
  List<dynamic>? get content;
}

@Schema()
abstract class $ModelInfo {
  List<String>? get versions;
  String? get label;
  Map<String, dynamic>? get configSchema;
  Map<String, dynamic>? get supports;
  String? get stage;
}

@Schema()
abstract class $ModelRequest {
  List<$Message> get messages;
  Map<String, dynamic>? get config;
  List<$ToolDefinition>? get tools;
  String? get toolChoice;
  $OutputConfig? get output;
  List<$DocumentData>? get docs;
}

@Schema()
abstract class $ModelResponse {
  $Message? get message;
  FinishReason get finishReason;
  String? get finishMessage;
  $RuntimeError? get error;
  double? get latencyMs;
  $GenerationUsage? get usage;
  Map<String, dynamic>? get custom;
  Map<String, dynamic>? get raw;
  $GenerateRequest? get request;
  $Operation? get operation;
}

@Schema()
abstract class $ModelResponseChunk {
  Role? get role;
  int? get index;
  List<$Part> get content;
  Map<String, dynamic>? get custom;
  bool? get aggregated;
}

@Schema()
abstract class $MiddlewareRef {
  String get name;
  Map<String, dynamic>? get config;
}

@Schema()
abstract class $RuntimeError {
  String? get status;
  String get message;
  Map<String, dynamic>? get details;
}

@Schema()
abstract class $GenerateResponse {
  $Message? get message;
  FinishReason? get finishReason;
  String? get finishMessage;
  $RuntimeError? get error;
  double? get latencyMs;
  $GenerationUsage? get usage;
  Map<String, dynamic>? get custom;
  Map<String, dynamic>? get raw;
  $GenerateRequest? get request;
  $Operation? get operation;
  List<$Candidate>? get candidates;
}

@Schema()
abstract class $GenerateRequest {
  List<$Message> get messages;
  Map<String, dynamic>? get config;
  List<$ToolDefinition>? get tools;
  String? get toolChoice;
  $OutputConfig? get output;
  List<$DocumentData>? get docs;
  double? get candidates;
}

@Schema()
abstract class $GenerationUsage {
  double? get inputTokens;
  double? get outputTokens;
  double? get totalTokens;
  double? get inputCharacters;
  double? get outputCharacters;
  double? get inputImages;
  double? get outputImages;
  double? get inputVideos;
  double? get outputVideos;
  double? get inputAudioFiles;
  double? get outputAudioFiles;
  Map<String, dynamic>? get custom;
  double? get thoughtsTokens;
  double? get cachedContentTokens;
}

@Schema()
abstract class $Operation {
  String? get action;
  String get id;
  bool? get done;
  Map<String, dynamic>? get output;
  Map<String, dynamic>? get error;
  Map<String, dynamic>? get metadata;
}

@Schema()
abstract class $OutputConfig {
  String? get format;
  Map<String, dynamic>? get schema;
  bool? get constrained;
  String? get contentType;
}

extension type FinishReason(String value) {
  static FinishReason get stop => FinishReason('stop');
  static FinishReason get length => FinishReason('length');
  static FinishReason get blocked => FinishReason('blocked');
  static FinishReason get aborted => FinishReason('aborted');
  static FinishReason get failed => FinishReason('failed');
  static FinishReason get interrupted => FinishReason('interrupted');
  static FinishReason get other => FinishReason('other');
  static FinishReason get unknown => FinishReason('unknown');
}

extension type Role(String value) {
  static Role get system => Role('system');
  static Role get user => Role('user');
  static Role get model => Role('model');
  static Role get tool => Role('tool');
}

@Schema()
abstract class $DocumentData {
  List<$Part> get content;
  Map<String, dynamic>? get metadata;
}

@Schema()
abstract class $GenerateActionOptions {
  String? get model;
  List<$DocumentData>? get docs;
  List<$Message> get messages;
  List<String>? get tools;
  List<String>? get resources;
  String? get toolChoice;
  Map<String, dynamic>? get config;
  $GenerateActionOutputConfig? get output;
  $GenerateResumeOptions? get resume;
  bool? get returnToolRequests;
  int? get maxTurns;
  String? get stepName;
  List<$MiddlewareRef>? get use;
}

@Schema()
abstract class $GenerateResumeOptions {
  List<$ToolResponsePart>? get respond;
  List<$ToolRequestPart>? get restart;
  Map<String, dynamic>? get metadata;
}

@Schema()
abstract class $GenerateActionOutputConfig {
  String? get format;
  String? get contentType;
  @AnyOf([bool, String])
  Object? get instructions;
  Map<String, dynamic>? get jsonSchema;
  bool? get constrained;
  bool? get defaultInstructions;
}

@Schema()
abstract class $EmbedRequest {
  List<$DocumentData> get input;
  Map<String, dynamic>? get options;
}

@Schema()
abstract class $EmbedResponse {
  List<$Embedding> get embeddings;
}

@Schema()
abstract class $Embedding {
  List<double> get embedding;
  Map<String, dynamic>? get metadata;
}

@Schema()
abstract class $ReflectionCancelActionParams {
  String get traceId;
}

@Schema()
abstract class $ReflectionCancelActionResponse {
  String get message;
}

@Schema()
abstract class $ReflectionConfigureParams {
  String? get telemetryServerUrl;
}

@Schema()
abstract class $ReflectionEndInputStreamParams {
  String get requestId;
}

@Schema()
abstract class $ReflectionListActionsResponse {
  Map<String, dynamic> get actions;
}

@Schema()
abstract class $ReflectionListValuesParams {
  String get type;
}

@Schema()
abstract class $ReflectionListValuesResponse {
  Map<String, dynamic> get values;
}

@Schema()
abstract class $ReflectionRegisterParams {
  String get id;
  int get pid;
  String? get name;
  String? get genkitVersion;
  double? get reflectionApiSpecVersion;
  List<String>? get envs;
}

@Schema()
abstract class $ReflectionRunActionParams {
  String? get runtimeId;
  String get key;
  dynamic get input;
  dynamic get init;
  dynamic get context;
  Map<String, dynamic>? get telemetryLabels;
  bool? get stream;
  bool? get streamInput;
}

@Schema()
abstract class $ReflectionRunActionStateParams {
  String get requestId;
  Map<String, dynamic>? get state;
}

@Schema()
abstract class $ReflectionSendInputStreamChunkParams {
  String get requestId;
  Map<String, dynamic>? get chunk;
}

@Schema()
abstract class $ReflectionStreamChunkParams {
  String get requestId;
  dynamic get chunk;
}

extension type AgentFinishReason(String value) {
  static AgentFinishReason get stop => AgentFinishReason('stop');
  static AgentFinishReason get length => AgentFinishReason('length');
  static AgentFinishReason get blocked => AgentFinishReason('blocked');
  static AgentFinishReason get interrupted => AgentFinishReason('interrupted');
  static AgentFinishReason get other => AgentFinishReason('other');
  static AgentFinishReason get unknown => AgentFinishReason('unknown');
  static AgentFinishReason get aborted => AgentFinishReason('aborted');
  static AgentFinishReason get detached => AgentFinishReason('detached');
  static AgentFinishReason get failed => AgentFinishReason('failed');
}

@Schema()
abstract class $AgentInit {
  String? get sessionId;
  String? get snapshotId;
  $SessionState? get state;
}

@Schema()
abstract class $AgentInput {
  bool? get detach;
  $Message? get message;
  $AgentResume? get resume;
}

@Schema()
abstract class $AgentResume {
  List<$ToolResponsePart>? get respond;
  List<$ToolRequestPart>? get restart;
}

@Schema()
abstract class $AgentOutput {
  String? get sessionId;
  String? get snapshotId;
  $SessionState? get state;
  $Message? get message;
  List<$Artifact>? get artifacts;
  AgentFinishReason? get finishReason;
  $AgentErrorInfo? get error;
}

@Schema()
abstract class $AgentErrorInfo {
  String? get status;
  String get message;
  Object? get details;
}

@Schema()
abstract class $AgentResult {
  $Message? get message;
  List<$Artifact>? get artifacts;
  AgentFinishReason? get finishReason;
}

@Schema()
abstract class $AgentStreamChunk {
  $ModelResponseChunk? get modelChunk;
  List<$JsonPatchOperation>? get customPatch;
  $Artifact? get artifact;
  $TurnEnd? get turnEnd;
}

@Schema()
abstract class $AgentAbortRequest {
  String get snapshotId;
}

@Schema()
abstract class $AgentAbortResponse {
  String get snapshotId;
  SnapshotStatus? get status;
}

@Schema()
abstract class $AgentMetadata {
  AgentStateManagement get stateManagement;
  bool get abortable;
  Map<String, dynamic>? get stateSchema;
}

extension type AgentStateManagement(String value) {
  static AgentStateManagement get server => AgentStateManagement('server');
  static AgentStateManagement get client => AgentStateManagement('client');
}

@Schema()
abstract class $TurnEnd {
  String? get snapshotId;
  AgentFinishReason? get finishReason;
}

@Schema()
abstract class $Artifact {
  String? get name;
  List<$Part> get parts;
  Map<String, dynamic>? get metadata;
}

@Schema()
abstract class $GetSnapshotDataInput {
  String? get snapshotId;
  String? get sessionId;
  bool? get metadataOnly;
}

extension type JsonPatchOp(String value) {
  static JsonPatchOp get add => JsonPatchOp('add');
  static JsonPatchOp get remove => JsonPatchOp('remove');
  static JsonPatchOp get replace => JsonPatchOp('replace');
  static JsonPatchOp get move => JsonPatchOp('move');
  static JsonPatchOp get copy => JsonPatchOp('copy');
  static JsonPatchOp get test => JsonPatchOp('test');
}

@Schema()
abstract class $JsonPatchOperation {
  JsonPatchOp get op;
  String get path;
  String? get from;
  Object? get value;
}

@Schema()
abstract class $SessionSnapshot {
  String get snapshotId;
  String? get sessionId;
  String? get parentId;
  String get createdAt;
  String? get updatedAt;
  String? get heartbeatAt;
  SnapshotStatus? get status;
  AgentFinishReason? get finishReason;
  $AgentErrorInfo? get error;
  $SessionState? get state;
}

@Schema()
abstract class $SessionState {
  String? get sessionId;
  List<$Message>? get messages;
  Object? get custom;
  List<$Artifact>? get artifacts;
}

extension type SnapshotStatus(String value) {
  static SnapshotStatus get pending => SnapshotStatus('pending');
  static SnapshotStatus get aborting => SnapshotStatus('aborting');
  static SnapshotStatus get completed => SnapshotStatus('completed');
  static SnapshotStatus get aborted => SnapshotStatus('aborted');
  static SnapshotStatus get failed => SnapshotStatus('failed');
  static SnapshotStatus get expired => SnapshotStatus('expired');
}
