name: middleware_sample
description: Genkit Middleware test app
publish_to: none
resolution: workspace
environment:
  sdk: ^3.10.0

dependencies:
  genkit: ^0.16.1
  genkit_google_genai: ^0.3.1
  genkit_middleware: ^0.6.1
  schemantic: ^0.2.2

dev_dependencies:
  build_runner: ^2.10.5
  test: ^1.29.0
